spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        user:
          user_retrieved:
            name: user_retrieved
        subscription:
          user_subscription:
            name: user_subscription
          user_unsubscription:
            name: user_unsubscription

messages:
  basename: messages

logging:
  level:
    root: info

client:
  skip_event:
    header: X-Skip-Event

server:
  port: 8080
